spring:
  profiles:
    active: dev
  # REDIS (RedisProperties)
  redis:
        host: 127.0.0.1
        port: 6379
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000
        timeout: 0
  ## Dubbo 服务消费者配置
  dubbo:
        application:
           name: provider
        registry:
           address: zookeeper://127.0.0.1:2181
        scan: com.example.demo.module
        monitor:
            protocol: registry
  # multipart (单次文件大小和单次文件总大小)
  servlet:
        multipart:
           max-file-size: 10MB
           max-request-size: 100MB
#mp
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    banner: false
    db-config:
      db-type: mysql
      id-type: uuid
      field-strategy: not_null